### ISSUE TITLE
I am writing to ask about your agree

### ISSUE THREAD

**Issue by rainairCC** [GreenMachine582/BSS-MachineLearning#1]
Hello,  I am a fresh graduate of National Taiwan University. I m really interested in your project here, and I would like to using this idea for my thesis reference. I would be grateful if you agree, Thank you in advance.

**Comment by GreenMachine582** [comment]
Hi @rainairCC, thanks for the recognition and request. This project was developed for my undergraduate group capstone project with the Univerity of Canberra, meaning that this idea cannot be used, however, you may reference it.
